//package graph
//
//import org.apache.spark.sql.types._
//import io.prophecy.libs._
//import io.prophecy.libs.UDFUtils._
//import io.prophecy.libs.Component._
//import io.prophecy.libs.DataHelpers._
//import io.prophecy.libs.SparkFunctions._
//import io.prophecy.libs.FixedFileFormatImplicits._
//import org.apache.spark.sql.ProphecyDataFrame._
//import org.apache.spark._
//import org.apache.spark.sql._
//import org.apache.spark.sql.functions._
//import graph._
//
//@Visual(id="Select_3", label="Select_3", x = 100, y = 100)
//object Visa {
//
//  def apply(spark: SparkSession, in: DataFrame): Reformat = {
//    import spark.implicits._
//    spark.udf.register("rejFlagSmsRfcUDF", rejFlagSmsRfcUDF)
//
//    val out = in.select(
//      expr("""`cmls_tran_cd`""").as("GMBS_B2_TRAN_CD"),
//      expr("""`cmls_mrch_regn_cd_drvd`""").as("GMBS_MRCH_REGN_CD"),
//      expr("""`cmls_dest_bin_typ`""").as("GMBS_BIN_TYP"),
//      expr("""CAST(`cmls_setlmt_svc_id` AS STRING)""").as("GMBS_SETLMT_SVC_ID"),
//      expr("""`cmls_reimb_attr`""").as("GMBS_REIMB_ATTR"),
//      expr("""CAST(`cmls_pos_chk_occurs` AS STRING)""").as("GMBS_POS_CHK_OCCURS"),
//      expr("""`cmls_ppd_crd_ind`""").as("GMBS_PPD_CRD_IND"),
//      expr("""`cmls_rtrn_rsn_flg`""").as("GMBS_RTN_FLG"),
//      expr("""`cmls_exprt_flg`""").as("GMBS_EXPRT_FLG"),
//      expr("""`cmls_coll_flg`""").as("GMBS_COLL_ONLY_FLG"),
//      expr("""CAST(`cmls_jp_pymt_mode` AS STRING)""").as("GMBS_JP_PYMT_MODE"),
//      expr("""`cmls_usage_cd`""").as("GMBS_USAGE_CD"),
//      expr("""`cmls_reqst_cps`""").as("GMBS_CPS_FLG"),
//      expr("""CAST(`cmls_jp_instalmt_pymt_cnt` AS STRING)""").as("GMBS_JP_INSTL_PYMT_CNT"),
//      expr("""`cmls_ssbc_curr_cd`""").as("GMBS_SSBC_CURR_CD"),
//      expr("""`cmls_tran_cd_qlfr`""").as("GMBS_TRAN_CD_QLFR"),
//      expr("""`cmls_curr_conv_ind`""").as("GMBS_CURR_CONV_IND"),
//      expr("""`cmls_prod_typ_cd_drvd`""").as("GMBS_PROD_TYP_CD"),
//      expr("""`cmls_sml_tkt_excptn_ind`""").as("GMBS_SML_TKT_EXCPTN_IND"),
//      expr("""`cmls_rptg_jrsdctn_prcg_elmt_drvd`""").as("GMBS_ELMT_RPTG_JRSDCTN_ID"),
//      expr("""`cmls_custm_prodct_grp_prcg_elmt_drvd`""").as("GMBS_ELMT_CUSTM_PROD_GRP_ID"),
//      expr("""`cmls_ntwrk_prcg_elmt_drvd`""").as("GMBS_ELMT_NTWRK_ID"),
//      expr("""`cmls_crdh_authntn_mthd_prcg_elmt_drvd`""").as("GMBS_ELMT_CRDH_AUTH_MTHD_ID"),
//      expr("""`cmls_acptnc_chnl_drvd`""").as("GMBS_ELMT_ACPTNC_CHNL_ID"),
//      expr("""`cmls_prcg_mrch_typ_grp_drvd`""").as("GMBS_ELMT_MRCH_TYP_GRP_ID"),
//      expr("""`cmls_tkt_size_ind_drvd`""").as("GMBS_ELMT_TKT_SIZE_ID"),
//      expr("""`cmls_prod_id_num_drvd`""").as("GMBS_PROD_ID_NUM"),
//      expr("""`cmls_tran_cd`""").as("GMBS_PROC_TRAN_CD"),
//      expr("""`cmls_ppd_sub_typ_cd_drvd`""").as("GMBS_PPD_SUB_TYP_CD"),
//      expr("""`cmls_pos_env_cd`""").as("GMBS_POS_ENV_CD"),
//      expr("""`cmls_posentry_mode_cd`""").as("GMBS_POSENTRY_MODE_CD"),
//      expr("""`cmls_crd_id_mthd_cd`""").as("GMBS_CRD_ID_MTH_CD"),
//      expr("""`cmls_setlmt_cd`""").as("GMBS_SETLMT_CD"),
//      expr("""`cmls_terml_authntn_cpbty_prcg_elmt_drvd`""").as("GMBS_ELMT_TERM_AUTH_CPBTY_ID"),
//      expr("""`cmls_jrsdctn_based_dscnt_ind`""").as("GMBS_PAISLEY_QUALIFIED"),
//      expr("""`cmls_mvv_dba_complnc_ind_drvd`""").as("GMBS_MVV_DBA_COMPLNC_IND_DRVD"),
//      expr("""`cmls_spcl_prc_elmt_mrch_typ_grp_no_mvv_id_drvd`""").as("GMBS_SPCL_PRC_ELMT_MRCH_TYP_GRP_NO_MVV_ID_DRVD"),
//      expr("""`cmls_aisa_elig_cd`""").as("GMBS_AISA_ELIG_CD"),
//      expr("""`cmls_iaf_elig_cd`""").as("GMBS_IAF_ELIG_CD"),
//      expr("""`cmls_isa_elig_cd`""").as("GMBS_ISA_ELIG_CD"),
//      expr("""`cmls_acqr_initd_sngl_curr_ind`""").as("GMBS_ACQR_INITD_SNGL_CURR_IND"),
//      expr("""CAST(`cmls_tokn_trans_ind` AS STRING)""").as("GMBS_TOKN_TRAN_IND"),
//      expr("""`cmls_tokn_typ_cd`""").as("GMBS_TOKN_TYP_CD"),
//      expr("""`cmls_bus_appl_id`""").as("GMBS_BUS_APPL_ID"),
//      expr("""CAST(`cmls_mmap_qlfd_tran_ind` AS STRING)""").as("GMBS_MMAP_QLFD_TRAN_IND"),
//      expr("""`cmls_tran_seq_id_drvd`""").as("CMLS_TRAN_SEQ_ID"),
//      expr("""`cmls_iaf_chrg_ind_typ`""").as("GMBS_IAF_CHRG_IND_TYP"),
//      expr("""`cmls_iaf_srchg_ind_typ`""").as("GMBS_IAF_SRCHG_IND_TYP"),
//      expr("""`cmls_b2b_acqr_fee_elg_ind`""").as("GMBS_B2B_ACQR_FEE_ELG_IND"),
//      expr("""`cmls_tran_procg_fee_ind`""").as("GMBS_TRAN_PROCG_FEE_IND"),
//      expr("""CAST(`cmls_acqr_ntwrk_id_criscros` AS STRING)""").as("GMBS_ACQR_NTWRK_ID_CRISCROS"),
//      expr("""CAST(`cmls_issr_ntwrk_id_criscros` AS STRING)""").as("GMBS_ISSR_NTWRK_ID_CRISCROS"),
//      expr("""`cmls_dcc_ind`""").as("GMBS_DCC_IND"),
//      expr("""`cmls_flxbl_cmsn_rt_qlfd_ind`""").as("GMBS_FLXBL_CMSN_RT_QLFD_IND"),
//      expr("""CAST(`cmls_srchg_amt` AS STRING)""").as("GMBS_SRCHG_AMT"),
//      expr("""`cmls_bnk_p2p_negt_rt_ind`""").as("GMBS_BNK_P2P_NEGT_RT_IND"),
//      expr("""`cmls_cut_num_drvd`""").as("gmbs_cut_num_drvd"),
//      expr("""`cmls_rptg_jrsdctn`""").as("GMBS_RPTG_JRSDCTN"),
//      expr("""CAST(`cmls_sms_msg_cls` AS STRING)""").as("GMBS_SMS_MSG_CLS"),
//      expr("""`cmls_proc_tran_cd`""").as("GMBS_PROC_CD"),
//      expr("""`cmls_resp_cd_drvd`""").as("GMBS_RESP_CD"),
//      expr("""`cmls_msg_rsn_cd_drvd`""").as("GMBS_SMS_MIS_CAS_RSN_CD"),
//      expr("""`cmls_posterm_cpbty_cd`""").as("GMBS_POSENTRY_CAP"),
//      expr("""`cmls_ntwrk_mgmt_cd`""").as("GMBS_SMS_NTWRK_MGMT_CD"),
//      expr("""CAST(`cmls_sms_preauth_time_lmt` AS STRING)""").as("GMBS_SMS_PREAUTH_TIME_LMT"),
//      expr("""`cmls_sms_file_upd_cd`""").as("GMBS_SMS_FILE_UPDT_CD"),
//      expr("""CAST(`cmls_posentry_mode_data` AS STRING)""").as("GMBS_POSENTRY_MODE_DATA"),
//      expr("""`cmls_proc_acct_typ_to_cd`""").as("GMBS_ACCT_TYP_TO"),
//      expr("""`cmls_sms_stop_ord_typ`""").as("GMBS_SMS_STOP_ORD_TYP"),
//      expr("""`cmls_stip_swtch_rsn_cd`""").as("GMBS_SMS_STIP_SW_RSN_CD"),
//      expr("""CAST(`cmls_dg_prtcptn_flg` AS STRING)""").as("GMBS_DG_PRTCPTN_FLG"),
//      expr("""`cmls_dg_tran_xcpt_flg_drvd`""").as("GMBS_DG_TRAN_XCPT_FLG"),
//      expr("""`cmls_acqr_sre_id_visa_proc_chrg`""").as("GMBS_VISA_PROC_CHRG_ACQR_SRE_ID"),
//      expr("""`cmls_acqr_stn_id_drvd`""").as("GMBS_ACQR_STN_FLG"),
//      expr("""`cmls_crd_id_mthd_cd`""").as("GMBS_CRD_ID_MTHD_CD"),
//      expr("""`cmls_dest_pcr`""").as("GMBS_FM_UPDATING_PCR"),
//      expr("""`cmls_criss_cros_ind`""").as("GMBS_CRISS_CROS_IND"),
//      expr("""`cmls_msg_fmt_dngrd_ind`""").as("GMBS_MSG_FMT_DNGRD_IND"),
//      expr("""`cmls_msg_fmt_upgrd_ind`""").as("GMBS_MSG_FMT_UPGRD_IND"),
//      expr("""CAST(`cmls_cam_perf_ind` AS STRING)""").as("GMBS_CAM_PERF_IND"),
//      expr("""CAST(`cmls_cam_rslt_not_actd_upon_ind` AS STRING)""").as("GMBS_CAM_RSLT_NOT_ACTD_UPON_IND"),
//      expr("""CAST(`cmls_dcvv_perf_ind` AS STRING)""").as("GMBS_DCVV_PERF_IND"),
//      expr("""CAST(`cmls_icvv_convrsn_perfd_ind` AS STRING)""").as("GMBS_ICVV_CONVRSN_PERFD_IND"),
//      expr("""CAST(`cmls_vmp_flg` AS STRING)""").as("GMBS_VMP_FLG"),
//      expr("""`cmls_affs_acqr_prtcptn_ind`""").as("GMBS_AFFS_ACQR_PRTCPTN_IND"),
//      expr("""`cmls_affs_issr_prtcptn_ind`""").as("GMBS_AFFS_ISSR_PRTCPTN_IND"),
//      expr("""`cmls_affs_tran_qual_ind`""").as("GMBS_AFFS_TRAN_QUAL_IND"),
//      expr("""CAST(`cmls_vta_ec_mrch_risk_snt_to_acqr_ind` AS STRING)""").as("GMBS_VTA_EC_MRCH_RISK_SNT_TO_ACQR_IND"),
//      expr("""CAST(`cmls_atm_tier_lvl_drvd` AS STRING)""").as("GMBS_ATM_TIER_LVL_DRVD"),
//      expr("""`cmls_oct_to_mrt_dngrd_flg`""").as("GMBS_OCT_TO_MRT_DNGRD_FLG"),
//      expr("""`cmls_vau_svc_id`""").as("GMBS_VAU_SVC_ID"),
//      expr("""CAST(`cmls_rt_vau_sta_cd` AS STRING)""").as("GMBS_RT_VAU_STA_CD"),
//      expr("""CAST(`cmls_vau_ppcs_upd_ind` AS STRING)""").as("GMBS_VAU_PPCS_UPD_IND"),
//      expr("""CAST(`cmls_tsp_tokn_ind` AS STRING)""").as("GMBS_TSP_TOKN_IND"),
//      expr("""`cmls_ve_mbr_intgrtn_sta`""").as("GMBS_VE_MBR_INTGRTN_STA"),
//      expr("""CAST(`cmls_incrct_atm_rteg_tbl_uniq_id` AS STRING)""").as("GMBS_INCRCT_ATM_RTEG_TBL_UNIQ_ID"),
//      expr("""CAST(`cmls_cvv2_convrsn_perfd_ind` AS STRING)""").as("GMBS_CVV2_CONVRSN_PERFD_IND"),
//      expr("""`cmls_chip_tran_cd`""").as("GMBS_B1ADVC_CCPS_TRAN_IND"),
//      expr("""`cmls_svc_cd`""").as("GMBS_SVC_CD"),
//      expr("""CAST(`cmls_dcvv2_genrtn_cnt` AS STRING)""").as("GMBS_DCVV2_GENRTN_CNT"),
//      expr("""`cmls_sms_crd_auth_resp_cd`""").as("GMBS_SMS_CRD_AUTH_RESP_CD"),
//      expr("""CAST(`cmls_tb_dcvv2_vldtn_perfd_ind` AS STRING)""").as("GMBS_TB_DCVV2_VLDTN_PERFD_IND"),
//      expr("""`cmls_bus_appl_id`""").as("GMBS_BUS_APPLN_ID"),
//      expr("""cmls_acct_num""").as("cmls_acct_num"),
//      expr("""cmls_acct_usage_cd""").as("cmls_acct_usage_cd"),
//      expr("""cmls_tran_cd""").as("cmls_tran_cd"),
//      expr("""cmls_mrch_regn_cd_drvd""").as("cmls_mrch_regn_cd_drvd"),
//      expr("""CAST(`cmls_srce_cib` AS STRING)""").as("cmls_srce_cib"),
//      expr("""CAST(`cmls_dest_cib` AS STRING)""").as("cmls_dest_cib"),
//      expr("""cmls_dest_bin_typ""").as("cmls_dest_bin_typ"),
//      expr("""CAST(`cmls_ntwrk_id` AS STRING)""").as("cmls_ntwrk_id"),
//      expr("""CAST(`cmls_setlmt_svc_id` AS STRING)""").as("cmls_setlmt_svc_id"),
//      expr("""cmls_reimb_attr""").as("cmls_reimb_attr"),
//      expr("""CAST(`cmls_mrch_catg_cd` AS STRING)""").as("cmls_mrch_catg_cd"),
//      expr("""cmls_srce_setlmt_curr_cd""").as("cmls_srce_setlmt_curr_cd"),
//      expr("""cmls_dest_setlmt_curr_cd""").as("cmls_dest_setlmt_curr_cd"),
//      expr("""CAST(`cmls_pos_chk_occurs` AS STRING)""").as("cmls_pos_chk_occurs"),
//      expr("""cmls_tran_drctn""").as("cmls_tran_drctn"),
//      expr("""cmls_ppd_crd_ind""").as("cmls_ppd_crd_ind"),
//      expr("""cmls_rtrn_rsn_flg""").as("cmls_rtrn_rsn_flg"),
//      expr("""cmls_exprt_flg""").as("cmls_exprt_flg"),
//      expr("""cmls_coll_flg""").as("cmls_coll_flg"),
//      expr("""CAST(`cmls_jp_pymt_mode` AS STRING)""").as("cmls_jp_pymt_mode"),
//      expr("""cmls_usage_cd""").as("cmls_usage_cd"),
//      expr("""cmls_reqst_cps""").as("cmls_reqst_cps"),
//      expr("""CAST(`cmls_jp_instalmt_pymt_cnt` AS STRING)""").as("cmls_jp_instalmt_pymt_cnt"),
//      expr("""cmls_ssbc_curr_cd""").as("cmls_ssbc_curr_cd"),
//      expr("""cmls_tran_cd_qlfr""").as("cmls_tran_cd_qlfr"),
//      expr("""cmls_curr_conv_ind""").as("cmls_curr_conv_ind"),
//      expr("""cmls_prod_typ_cd_drvd""").as("cmls_prod_typ_cd_drvd"),
//      expr("""cmls_sml_tkt_excptn_ind""").as("cmls_sml_tkt_excptn_ind"),
//      expr("""cmls_rptg_jrsdctn_prcg_elmt_drvd""").as("cmls_rptg_jrsdctn_prcg_elmt_drvd"),
//      expr("""cmls_custm_prodct_grp_prcg_elmt_drvd""").as("cmls_custm_prodct_grp_prcg_elmt_drvd"),
//      expr("""cmls_ntwrk_prcg_elmt_drvd""").as("cmls_ntwrk_prcg_elmt_drvd"),
//      expr("""cmls_crdh_authntn_mthd_prcg_elmt_drvd""").as("cmls_crdh_authntn_mthd_prcg_elmt_drvd"),
//      expr("""cmls_acptnc_chnl_drvd""").as("cmls_acptnc_chnl_drvd"),
//      expr("""cmls_prcg_mrch_typ_grp_drvd""").as("cmls_prcg_mrch_typ_grp_drvd"),
//      expr("""cmls_tkt_size_ind_drvd""").as("cmls_tkt_size_ind_drvd"),
//      expr("""cmls_prod_id_num_drvd""").as("cmls_prod_id_num_drvd"),
//      expr("""cmls_ppd_sub_typ_cd_drvd""").as("cmls_ppd_sub_typ_cd_drvd"),
//      expr("""cmls_pos_env_cd""").as("cmls_pos_env_cd"),
//      expr("""cmls_posentry_mode_cd""").as("cmls_posentry_mode_cd"),
//      expr("""cmls_mrch_vrfcn_val""").as("cmls_mrch_vrfcn_val"),
//      expr("""cmls_crd_id_mthd_cd""").as("cmls_crd_id_mthd_cd"),
//      expr("""cmls_setlmt_cd""").as("cmls_setlmt_cd"),
//      expr("""cmls_terml_authntn_cpbty_prcg_elmt_drvd""").as("cmls_terml_authntn_cpbty_prcg_elmt_drvd"),
//      expr("""cmls_jrsdctn_based_dscnt_ind""").as("cmls_jrsdctn_based_dscnt_ind"),
//      expr("""cmls_mvv_dba_complnc_ind_drvd""").as("cmls_mvv_dba_complnc_ind_drvd"),
//      expr("""cmls_spcl_prc_elmt_mrch_typ_grp_no_mvv_id_drvd""").as("cmls_spcl_prc_elmt_mrch_typ_grp_no_mvv_id_drvd"),
//      expr("""CAST(`cmls_mrch_dba_id_drvd` AS STRING)""").as("cmls_mrch_dba_id_drvd"),
//      expr("""cmls_aisa_elig_cd""").as("cmls_aisa_elig_cd"),
//      expr("""cmls_iaf_elig_cd""").as("cmls_iaf_elig_cd"),
//      expr("""cmls_isa_elig_cd""").as("cmls_isa_elig_cd"),
//      expr("""cmls_acqr_initd_sngl_curr_ind""").as("cmls_acqr_initd_sngl_curr_ind"),
//      expr("""CAST(`cmls_tokn_trans_ind` AS STRING)""").as("cmls_tokn_trans_ind"),
//      expr("""cmls_tokn_typ_cd""").as("cmls_tokn_typ_cd"),
//      expr("""cmls_bus_appl_id""").as("cmls_bus_appl_id"),
//      expr("""CAST(`cmls_destn_cib_regn` AS STRING)""").as("cmls_destn_cib_regn"),
//      expr("""CAST(`cmls_mmap_qlfd_tran_ind` AS STRING)""").as("cmls_mmap_qlfd_tran_ind"),
//      expr("""cmls_tran_seq_id_drvd""").as("cmls_tran_seq_id_drvd"),
//      expr("""cmls_chbk_rsn_cd""").as("cmls_chbk_rsn_cd"),
//      expr("""cmls_iaf_chrg_ind_typ""").as("cmls_iaf_chrg_ind_typ"),
//      expr("""cmls_iaf_srchg_ind_typ""").as("cmls_iaf_srchg_ind_typ"),
//      expr("""cmls_b2b_acqr_fee_elg_ind""").as("cmls_b2b_acqr_fee_elg_ind"),
//      expr("""cmls_tran_procg_fee_ind""").as("cmls_tran_procg_fee_ind"),
//      expr("""CAST(`cmls_acqr_ntwrk_id_criscros` AS STRING)""").as("cmls_acqr_ntwrk_id_criscros"),
//      expr("""CAST(`cmls_issr_ntwrk_id_criscros` AS STRING)""").as("cmls_issr_ntwrk_id_criscros"),
//      expr("""cmls_dcc_ind""").as("cmls_dcc_ind"),
//      expr("""cmls_flxbl_cmsn_rt_qlfd_ind""").as("cmls_flxbl_cmsn_rt_qlfd_ind"),
//      expr("""CAST(`cmls_srchg_amt` AS STRING)""").as("cmls_srchg_amt"),
//      expr("""cmls_bnk_p2p_negt_rt_ind""").as("cmls_bnk_p2p_negt_rt_ind"),
//      expr("""cmls_cut_num_drvd""").as("cmls_cut_num_drvd"),
//      expr("""CASE WHEN ((`cmls_tran_drctn` = 'SS') AND (`cmls_msg_fmt_dngrd_ind` = '1')) THEN `cmls_dest_rcvd_reqst_advc_msg_typ` ELSE `cmls_sms_req_msg_typ` END""").as("CMLS_SMS_REQ_MSG_TYP"),
//      expr("""CASE WHEN ((`cmls_tran_drctn` = 'SS') AND (`cmls_msg_fmt_dngrd_ind` = '1')) THEN `cmls_dest_rcvd_reqst_advc_origl_msg_typ` ELSE `CMLS_SMS_ORIG_MSG_TYP` END""").as("CMLS_SMS_ORIG_MSG_TYP"),
//      expr("""CAST(`cmls_srce_bin` AS STRING)""").as("cmls_srce_bin"),
//      expr("""cmls_rptg_jrsdctn""").as("cmls_rptg_jrsdctn"),
//      expr("""CAST(`cmls_sms_msg_cls` AS STRING)""").as("cmls_sms_msg_cls"),
//      expr("""cmls_proc_tran_cd""").as("cmls_proc_tran_cd"),
//      expr("""cmls_resp_cd_drvd""").as("cmls_resp_cd_drvd"),
//      expr("""cmls_msg_rsn_cd_drvd""").as("cmls_msg_rsn_cd_drvd"),
//      expr("""cmls_posterm_cpbty_cd""").as("cmls_posterm_cpbty_cd"),
//      expr("""cmls_ntwrk_mgmt_cd""").as("cmls_ntwrk_mgmt_cd"),
//      expr("""CAST(`cmls_sms_preauth_time_lmt` AS STRING)""").as("cmls_sms_preauth_time_lmt"),
//      expr("""cmls_sms_file_upd_cd""").as("cmls_sms_file_upd_cd"),
//      expr("""CAST(`cmls_posentry_mode_data` AS STRING)""").as("cmls_posentry_mode_data"),
//      expr("""cmls_proc_acct_typ_to_cd""").as("cmls_proc_acct_typ_to_cd"),
//      expr("""cmls_sms_stop_ord_typ""").as("cmls_sms_stop_ord_typ"),
//      expr("""cmls_stip_swtch_rsn_cd""").as("cmls_stip_swtch_rsn_cd"),
//      expr("""CAST(`cmls_dg_prtcptn_flg` AS STRING)""").as("cmls_dg_prtcptn_flg"),
//      expr("""cmls_dg_tran_xcpt_flg_drvd""").as("cmls_dg_tran_xcpt_flg_drvd"),
//      expr("""CAST(`cmls_dg_ntwrk_chrg_acqr_sre_id` AS STRING)""").as("cmls_dg_ntwrk_chrg_acqr_sre_id"),
//      expr("""cmls_intrchg_fee_acqr_sre_id""").as("cmls_intrchg_fee_acqr_sre_id"),
//      expr("""cmls_acqr_sre_id_visa_proc_chrg""").as("cmls_acqr_sre_id_visa_proc_chrg"),
//      expr("""cmls_acqr_stn_id_drvd""").as("cmls_acqr_stn_id_drvd"),
//      expr("""cmls_vdps_acqr_bin_migr_id""").as("cmls_vdps_acqr_bin_migr_id"),
//      expr("""cmls_vdps_issr_bin_migr_id""").as("cmls_vdps_issr_bin_migr_id"),
//      expr("""CAST(`cmls_partial_auth_ind` AS STRING)""").as("cmls_partial_auth_ind"),
//      expr("""cmls_pin_tran_flg""").as("cmls_pin_tran_flg"),
//      expr("""CAST(`cmls_pin_vrfcn_flg` AS STRING)""").as("cmls_pin_vrfcn_flg"),
//      expr("""cmls_intnl_svc_id""").as("cmls_intnl_svc_id"),
//      expr("""cmls_spcl_rte_ind""").as("cmls_spcl_rte_ind"),
//      expr("""cmls_lcs_act_tst_flg""").as("cmls_lcs_act_tst_flg"),
//      expr("""cmls_dest_pcr""").as("cmls_dest_pcr"),
//      expr("""cmls_criss_cros_ind""").as("cmls_criss_cros_ind"),
//      expr("""cmls_msg_fmt_dngrd_ind""").as("cmls_msg_fmt_dngrd_ind"),
//      expr("""cmls_msg_fmt_upgrd_ind""").as("cmls_msg_fmt_upgrd_ind"),
//      expr("""CAST(`cmls_cam_perf_ind` AS STRING)""").as("cmls_cam_perf_ind"),
//      expr("""CAST(`cmls_cam_rslt_not_actd_upon_ind` AS STRING)""").as("cmls_cam_rslt_not_actd_upon_ind"),
//      expr("""CAST(`cmls_dcvv_perf_ind` AS STRING)""").as("cmls_dcvv_perf_ind"),
//      expr("""CAST(`cmls_icvv_convrsn_perfd_ind` AS STRING)""").as("cmls_icvv_convrsn_perfd_ind"),
//      expr("""CAST(`cmls_vmp_flg` AS STRING)""").as("cmls_vmp_flg"),
//      expr("""cmls_affs_acqr_prtcptn_ind""").as("cmls_affs_acqr_prtcptn_ind"),
//      expr("""cmls_affs_issr_prtcptn_ind""").as("cmls_affs_issr_prtcptn_ind"),
//      expr("""cmls_affs_tran_qual_ind""").as("cmls_affs_tran_qual_ind"),
//      expr("""CAST(`cmls_vta_ec_mrch_risk_snt_to_acqr_ind` AS STRING)""").as("cmls_vta_ec_mrch_risk_snt_to_acqr_ind"),
//      expr("""CAST(`cmls_atm_tier_lvl_drvd` AS STRING)""").as("cmls_atm_tier_lvl_drvd"),
//      expr("""cmls_oct_to_mrt_dngrd_flg""").as("cmls_oct_to_mrt_dngrd_flg"),
//      expr("""cmls_vau_svc_id""").as("cmls_vau_svc_id"),
//      expr("""CAST(`cmls_rt_vau_sta_cd` AS STRING)""").as("cmls_rt_vau_sta_cd"),
//      expr("""CAST(`cmls_vau_ppcs_upd_ind` AS STRING)""").as("cmls_vau_ppcs_upd_ind"),
//      expr("""CAST(`cmls_tsp_tokn_ind` AS STRING)""").as("cmls_tsp_tokn_ind"),
//      expr("""cmls_ve_mbr_intgrtn_sta""").as("cmls_ve_mbr_intgrtn_sta"),
//      expr("""CAST(`cmls_incrct_atm_rteg_tbl_uniq_id` AS STRING)""").as("cmls_incrct_atm_rteg_tbl_uniq_id"),
//      expr("""CAST(`cmls_cvv2_convrsn_perfd_ind` AS STRING)""").as("cmls_cvv2_convrsn_perfd_ind"),
//      expr("""cmls_chip_tran_cd""").as("cmls_chip_tran_cd"),
//      expr("""cmls_svc_cd""").as("cmls_svc_cd"),
//      expr("""CAST(`cmls_dcvv2_genrtn_cnt` AS STRING)""").as("cmls_dcvv2_genrtn_cnt"),
//      expr("""cmls_sms_crd_auth_resp_cd""").as("cmls_sms_crd_auth_resp_cd"),
//      expr("""CAST(`cmls_tb_dcvv2_vldtn_perfd_ind` AS STRING)""").as("cmls_tb_dcvv2_vldtn_perfd_ind"),
//      expr("""cmls_cpd_dt""").as("cmls_cpd_dt"),
//      expr("""CAST(`cmls_mult_curr_setlmt_chrg_amt_sc` AS STRING)""").as("cmls_mult_curr_setlmt_chrg_amt_sc"),
//      expr("""cmls_rec_typ""").as("cmls_rec_typ"),
//      expr("""cmls_origtr_submtd_reqst_advc_origl_msg_typ""").as("cmls_origtr_submtd_reqst_advc_origl_msg_typ"),
//      expr("""cmls_dest_rcvd_reqst_advc_origl_msg_typ""").as("cmls_dest_rcvd_reqst_advc_origl_msg_typ"),
//      expr("""cmls_rtrn_rsn_cd""").as("cmls_rtrn_rsn_cd"),
//      expr("""cmls_tsp_bid""").as("cmls_tsp_bid"),
//      expr("""cmls_addl_trc_data_iso""").as("cmls_addl_trc_data_iso"),
//      expr("""CAST(`cmls_issr_affl_bin_ntwrk_id` AS STRING)""").as("cmls_issr_affl_bin_ntwrk_id"),
//      expr("""CAST(`cmls_acqr_affl_bin_ntwrk_id` AS STRING)""").as("cmls_acqr_affl_bin_ntwrk_id"),
//      expr("""cmls_xcpt_chrg_ind""").as("cmls_xcpt_chrg_ind"),
//      expr("""CAST(`cmls_acqr_ioi_amt_sc` AS STRING)""").as("cmls_acqr_ioi_amt_sc"),
//      expr("""CAST(`cmls_dfcfid_srce_procg_chrg_in_sc` AS STRING)""").as("cmls_dfcfid_srce_procg_chrg_in_sc"),
//      expr("""cmls_bus_appl_cd""").as("cmls_bus_appl_cd"),
//      expr("""cmls_sms_cas_proc_setlmt_id""").as("cmls_sms_cas_proc_setlmt_id"),
//      expr("""cmls_sms_mis_proc_setlmt_id""").as("cmls_sms_mis_proc_setlmt_id"),
//      expr("""CAST(`cmls_sms_dest_appl_proc` AS STRING)""").as("cmls_sms_dest_appl_proc"),
//      expr("""cmls_mrch_nm""").as("cmls_mrch_nm"),
//      expr("""cmls_rtrn_rsn_cd_1""").as("cmls_rtrn_rsn_cd_1"),
//      expr("""CAST(`cmls_issr_irf_ssbc` AS STRING)""").as("cmls_issr_irf_ssbc"),
//      expr("""CAST(`cmls_acqr_irf_ssbc` AS STRING)""").as("cmls_acqr_irf_ssbc"),
//      expr("""CAST(`cmls_dg_acqr_chrg_amt_sc` AS STRING)""").as("cmls_dg_acqr_chrg_amt_sc"),
//      expr("""CAST(`cmls_giv_updd_flg` AS STRING)""").as("cmls_giv_updd_flg"),
//      expr("""CAST(`cmls_sms_issr_bin_ctry_cd` AS STRING)""").as("cmls_sms_issr_bin_ctry_cd"),
//      expr("""cmls_auth_only_ind""").as("cmls_auth_only_ind"),
//      expr("""CAST(`cmls_issr_procr_affl_id` AS STRING)""").as("cmls_issr_procr_affl_id"),
//      expr("""CAST(`cmls_acqr_vss_procr_affl_bin_ntwrk_id` AS STRING)""").as("cmls_acqr_vss_procr_affl_bin_ntwrk_id"),
//      expr("""cmls_auth_srce_cd""").as("cmls_auth_srce_cd"),
//      expr("""CAST(`cmls_issr_fee_amt_reducn_ssbc` AS STRING)""").as("cmls_issr_fee_amt_reducn_ssbc"),
//      expr("""CAST(`cmls_acqr_fee_amt_reducn_ssbc` AS STRING)""").as("cmls_acqr_fee_amt_reducn_ssbc"),
//      expr("""cmls_tran_srce_cd""").as("cmls_tran_srce_cd"),
//      expr("""cmls_issr_chrg_flg""").as("cmls_issr_chrg_flg"),
//      expr("""cmls_tran_coll_from_flg""").as("cmls_tran_coll_from_flg"),
//      expr("""cmls_dest_flg_drvd""").as("cmls_dest_flg_drvd"),
//      expr("""CAST(`cmls_dest_bin` AS STRING)""").as("cmls_dest_bin"),
//      expr("""cmls_sms_acqr_bin_ctry_cd""").as("cmls_sms_acqr_bin_ctry_cd"),
//      expr("""CAST(`cmls_tran_id` AS STRING)""").as("cmls_tran_id"),
//      expr("""cmls_tokn_reqstr_id""").as("cmls_tokn_reqstr_id"),
//      expr("""CAST(`cmls_acqr_bin_ownr_bus_id_drvd` AS STRING)""").as("cmls_acqr_bin_ownr_bus_id_drvd"),
//      expr("""cmls_acqr_bin_ownr_bus_id_ctry_cd_drvd""").as("cmls_acqr_bin_ownr_bus_id_ctry_cd_drvd"),
//      expr("""cmls_dest_sre_id""").as("cmls_dest_sre_id"),
//      expr("""cmls_srce_sre_id""").as("cmls_srce_sre_id"),
//      expr("""CAST(`cmls_nspk_fallbk_procg_rsn_cd` AS STRING)""").as("cmls_nspk_fallbk_procg_rsn_cd"),
//      expr("""cmls_sms_tgt_file_nm""").as("cmls_sms_tgt_file_nm"),
//      expr("""cmls_prod_id_cd_drvd""").as("cmls_prod_id_cd_drvd"),
//      expr("""CAST(`cmls_us_cdi_tran_amt` AS STRING)""").as("cmls_us_cdi_tran_amt"),
//      expr("""CAST(`cmls_acqr_pcr` AS STRING)""").as("cmls_acqr_pcr"),
//      expr("""CAST(`cmls_issr_pcr` AS STRING)""").as("cmls_issr_pcr"),
//      expr("""cmls_b1advc_inq_ctr""").as("cmls_b1advc_inq_ctr"),
//      expr("""cmls_eci_moto_cd""").as("cmls_eci_moto_cd"),
//      expr("""cmls_chip_tran_typ""").as("cmls_chip_tran_typ"),
//      expr("""CAST(`cmls_multinatl_acqr_pgm_ctry_cd_drvd` AS STRING)""").as("cmls_multinatl_acqr_pgm_ctry_cd_drvd"),
//      expr("""cmls_srce_bin_ctry_cd_drvd""").as("cmls_srce_bin_ctry_cd_drvd"),
//      expr("""CMLS_DEST_BIN_CTRY_CD_DRVD""").as("CMLS_DEST_BIN_CTRY_CD_DRVD"),
//      expr("""cmls_srce_bin_regn_cd_drvd""").as("cmls_srce_bin_regn_cd_drvd"),
//      expr("""cmls_srce_cib_ctry_cd_drvd""").as("cmls_srce_cib_ctry_cd_drvd"),
//      expr("""cmls_srce_cib_regn_cd_drvd""").as("cmls_srce_cib_regn_cd_drvd"),
//      expr("""CAST(`cmls_ioi_sa_srce_amt_sc` AS STRING)""").as("cmls_ioi_sa_srce_amt_sc"),
//      expr("""CAST(`cmls_acqr_fee_reducn_chrg_typ` AS STRING)""").as("cmls_acqr_fee_reducn_chrg_typ"),
//      expr("""cmls_poscond_cd""").as("cmls_poscond_cd"),
//      expr("""cmls_srce_curr_cd""").as("cmls_srce_curr_cd"),
//      expr("""cmls_dest_curr_cd""").as("cmls_dest_curr_cd"),
//      expr("""cmls_dest_bin_regn_cd_drvd""").as("cmls_dest_bin_regn_cd_drvd"),
//      expr("""cmls_us_leg_regld_tran_ind""").as("cmls_us_leg_regld_tran_ind"),
//      expr("""cmls_us_leg_regld_issr_cd""").as("cmls_us_leg_regld_issr_cd"),
//      expr("""cmls_us_leg_regld_issr_cd_drvd""").as("cmls_us_leg_regld_issr_cd_drvd"),
//      expr("""cmls_crd_typ_cd""").as("cmls_crd_typ_cd"),
//      expr("""cmls_prod_brnd_cd_drvd""").as("cmls_prod_brnd_cd_drvd"),
//      expr("""cmls_prod_brnd_mvisa_cd_drvd""").as("cmls_prod_brnd_mvisa_cd_drvd"),
//      expr("""cmls_acct_prod_id""").as("cmls_acct_prod_id"),
//      expr("""cmls_prod_id_mvisa_cd""").as("cmls_prod_id_mvisa_cd"),
//      expr("""cmls_acct_fundg_srce_cd""").as("cmls_acct_fundg_srce_cd"),
//      expr("""cmls_acct_fundg_srce_mvisa_cd""").as("cmls_acct_fundg_srce_mvisa_cd"),
//      expr("""cmls_acct_fundg_subtyp_cd""").as("cmls_acct_fundg_subtyp_cd"),
//      expr("""cmls_acct_fundg_subtyp_mvisa_cd_drvd""").as("cmls_acct_fundg_subtyp_mvisa_cd_drvd"),
//      expr("""cmls_prod_id_subtyp_cd""").as("cmls_prod_id_subtyp_cd"),
//      expr("""cmls_prod_id_subtyp_mvisa_cd""").as("cmls_prod_id_subtyp_mvisa_cd"),
//      expr("""cmls_acct_lvl_procg_cd_drvd""").as("cmls_acct_lvl_procg_cd_drvd"),
//      expr("""cmls_acct_lvl_procg_mvisa_cd_drvd""").as("cmls_acct_lvl_procg_mvisa_cd_drvd"),
//      expr("""CAST(`cmls_tif_amt_sc` AS STRING)""").as("cmls_tif_amt_sc"),
//      expr("""cmls_kyc_mixed_ind_drvd""").as("cmls_kyc_mixed_ind_drvd"),
//      expr("""cmls_kyc_mixed_mvisa_ind_drvd""").as("cmls_kyc_mixed_mvisa_ind_drvd"),
//      expr("""cmls_prod_id_cls_mvisa_cd_drvd""").as("cmls_prod_id_cls_mvisa_cd_drvd"),
//      expr("""cmls_prod_id_cls_cd_drvd""").as("cmls_prod_id_cls_cd_drvd"),
//      expr("""cmls_prod_id_pltfrm_mvisa_cd_drvd""").as("cmls_prod_id_pltfrm_mvisa_cd_drvd"),
//      expr("""cmls_prod_id_pltfrm_cd_drvd""").as("cmls_prod_id_pltfrm_cd_drvd"),
//      expr("""cmls_prod_id_schm_cd_drvd""").as("cmls_prod_id_schm_cd_drvd"),
//      expr("""cmls_prod_id_schm_mvisa_cd_drvd""").as("cmls_prod_id_schm_mvisa_cd_drvd"),
//      expr("""cmls_xbrdr_ind""").as("cmls_xbrdr_ind"),
//      expr("""cmls_srce_of_tran_flg""").as("cmls_srce_of_tran_flg"),
//      expr("""CAST(`cmls_mrch_ctry_cd_num_drvd` AS STRING)""").as("cmls_mrch_ctry_cd_num_drvd"),
//      expr("""CAST(`cmls_acqr_ioi_amt_usd` AS STRING)""").as("cmls_acqr_ioi_amt_usd"),
//      expr("""CAST(`cmls_setlmt_srce_amt_usd` AS STRING)""").as("cmls_setlmt_srce_amt_usd"),
//      expr("""cmls_origtr_submtd_reqst_advc_msg_typ""").as("cmls_origtr_submtd_reqst_advc_msg_typ"),
//      expr("""cmls_dest_rcvd_reqst_advc_msg_typ""").as("cmls_dest_rcvd_reqst_advc_msg_typ"),
//      expr("""CAST(`cmls_acqr_portn_fee_sc` AS STRING)""").as("cmls_acqr_portn_fee_sc"),
//      expr("""CAST(`cmls_acqr_regn_isa_allocn_amt_ssbc` AS STRING)""").as("cmls_acqr_regn_isa_allocn_amt_ssbc"),
//      expr("""CAST(`cmls_issr_portn_fee_sc` AS STRING)""").as("cmls_issr_portn_fee_sc"),
//      expr("""CAST(`cmls_issr_regn_isa_allocn_amt_ssbc` AS STRING)""").as("cmls_issr_regn_isa_allocn_amt_ssbc"),
//      expr("""CAST(`cmls_cshbk_amt_usd` AS STRING)""").as("cmls_cshbk_amt_usd"),
//      expr("""cmls_spcl_atm_fee_ind""").as("cmls_spcl_atm_fee_ind"),
//      expr("""CAST(`cmls_issr_ttl_isa_amt_sc` AS STRING)""").as("cmls_issr_ttl_isa_amt_sc"),
//      expr("""CAST(`cmls_acqr_aisa_amt_sc` AS STRING)""").as("cmls_acqr_aisa_amt_sc"),
//      expr("""cmls_acqr_aisa_chrg_ind""").as("cmls_acqr_aisa_chrg_ind"),
//      expr("""CAST(`cmls_ecom_iaf_amt_sc` AS STRING)""").as("cmls_ecom_iaf_amt_sc"),
//      expr("""cmls_cmcrd_enh_mrch_sector""").as("cmls_cmcrd_enh_mrch_sector"),
//      expr("""cmls_appl_cd""").as("cmls_appl_cd"),
//      expr("""CAST(`cmls_srce_amt_usd` AS STRING)""").as("cmls_srce_amt_usd"),
//      expr("""CAST(`cmls_srce_amt` AS STRING)""").as("cmls_srce_amt"),
//      expr("""cmls_issr_pcr_regn_cd_drvd""").as("cmls_issr_pcr_regn_cd_drvd"),
//      expr("""cmls_acqr_pcr_regn_cd_drvd""").as("cmls_acqr_pcr_regn_cd_drvd"),
//      expr("""cmls_acqr_pcr_ctry_cd_drvd""").as("cmls_acqr_pcr_ctry_cd_drvd"),
//      expr("""cmls_issr_pcr_ctry_cd_drvd""").as("cmls_issr_pcr_ctry_cd_drvd"),
//      expr("""cmls_issr_affl_bin_regn_cd_drvd""").as("cmls_issr_affl_bin_regn_cd_drvd"),
//      expr("""cmls_acqr_affl_bin_regn_cd_drvd""").as("cmls_acqr_affl_bin_regn_cd_drvd"),
//      expr("""cmls_acqr_affl_bin_ctry_cd_drvd""").as("cmls_acqr_affl_bin_ctry_cd_drvd"),
//      expr("""cmls_issr_affl_bin_ctry_cd_drvd""").as("cmls_issr_affl_bin_ctry_cd_drvd"),
//      expr("""CAST(`cmls_amt_visa_internal` AS STRING)""").as("cmls_amt_visa_internal"),
//      expr("""CAST(`cmls_origtr_submtd_reqst_advc_tran_amt_usd` AS STRING)""").as("cmls_origtr_submtd_reqst_advc_tran_amt_usd"),
//      expr("""CMLS_ADVC_REC_ID""").as("CMLS_ADVC_REC_ID"),
//      expr("""CMLS_ACCT_REGN_CD_DRVD""").as("CMLS_ACCT_REGN_CD_DRVD"),
//      expr("""cmls_acct_ctry_cd_drvd""").as("cmls_acct_ctry_cd_drvd"),
//      expr("""CAST(`cmls_issr_visa_proc_chrg_amt_sc` AS STRING)""").as("cmls_issr_visa_proc_chrg_amt_sc"),
//      expr("""CAST(`cmls_acqr_visa_proc_chrg_amt_sc` AS STRING)""").as("cmls_acqr_visa_proc_chrg_amt_sc"),
//      expr("""CMLS_STIP_ADVC_CD""").as("CMLS_STIP_ADVC_CD"),
//      expr("""CMLS_FEECOLL_TXT""").as("CMLS_FEECOLL_TXT"),
//      expr("""cmls_mvv_visa_asgnd""").as("cmls_mvv_visa_asgnd"),
//      expr("""cmls_mvv_mrch_asgnd""").as("cmls_mvv_mrch_asgnd"),
//      expr("""CAST(`CMLS_SRCE_CIB_REGN` AS STRING)""").as("CMLS_SRCE_CIB_REGN"),
//      expr("""CAST(`cmls_issr_affl_rteg_ntwrk_id` AS STRING)""").as("cmls_issr_affl_rteg_ntwrk_id"),
//      expr("""CAST(`cmls_acqr_affl_rteg_ntwrk_id` AS STRING)""").as("cmls_acqr_affl_rteg_ntwrk_id"),
//      expr("""CMLS_REQST_MSG_SRCE_STN_ID""").as("CMLS_REQST_MSG_SRCE_STN_ID"),
//      expr("""CMLS_CRD_ACPTR_ID""").as("CMLS_CRD_ACPTR_ID"),
//      expr("""cmls_mrch_ctry_alpha""").as("cmls_mrch_ctry_alpha"),
//      expr("""CAST(`CMLS_TIME_RESP_SENT` AS STRING)""").as("CMLS_TIME_RESP_SENT"),
//      expr("""CMLS_SUSPECTED_FRD_RESP_CD""").as("CMLS_SUSPECTED_FRD_RESP_CD"),
//      expr("""CMLS_VIP_DERV_ACQR_SRE_ID""").as("CMLS_VIP_DERV_ACQR_SRE_ID"),
//      expr("""cmls_issr_bin_ctry_cd_drvd""").as("cmls_issr_bin_ctry_cd_drvd"),
//      expr("""CMLS_ADDL_TRC_DATA_ISO_RAW""").as("CMLS_ADDL_TRC_DATA_ISO_RAW"),
//      expr("""CMLS_MSG_RESP_SNT_TS""").as("CMLS_MSG_RESP_SNT_TS"),
//      expr("""CMLS_VDPS_ACQR_BIN_MIGR_ID_RAW""").as("CMLS_VDPS_ACQR_BIN_MIGR_ID_RAW"),
//      expr("""CMLS_VDPS_ISSR_BIN_MIGR_ID_RAW""").as("CMLS_VDPS_ISSR_BIN_MIGR_ID_RAW"),
//      expr("""(IF(((`CMLS_SRCE_CIB` IS NULL) OR (`CMLS_NSPK_FALLBK_PROCG_RSN_CD` IS NULL)), CAST(NULL AS INT), rejFlagSmsRfcUDF(CMLS_DEST_FLG, CMLS_VE_CS_JRSDCTN_CD_ENR, CMLS_SRCE_CIB, CMLS_NSPK_FALLBK_PROCG_RSN_CD, CMLS_VIP_RSI_MSG_CATGY, CMLS_TRAN_DRCTN, CMLS_SMS_REQ_MSG_TYP, CMLS_REC_TYP)))""").as("CMLS_REJ_FLAG"),
//      lit(1).as("CMLS_RECORD_INDEX_DRVD"),
//      expr("""`CMLS_SMS_ORIG_MSG_TYP`""").as("CMLS_ORIGL_MSG_TYP"),
//      expr("""`CMLS_VIP_RSI_MSG_CATGY`""").as("CMLS_MSG_CATG"),
//      expr("""CASE WHEN ((`cmls_srce_bin` = 500099) AND (`cmls_srce_cib` = 500099)) THEN '01' ELSE `cmls_srce_bin_regn_cd` END""").as("cmls_srce_bin_regn_cd"),
//      expr("""CASE WHEN ((`cmls_srce_bin` = 500099) AND (`cmls_srce_cib` = 500099)) THEN '001' ELSE CAST(`cmls_srce_bin_zone_cd` AS STRING) END""").as("cmls_srce_bin_zone_cd"),
//      expr("""CASE WHEN ((`cmls_dest_bin` = 500099) AND (`cmls_dest_cib` = 500099)) THEN '01' ELSE `cmls_dest_bin_regn_cd` END""").as("cmls_dest_bin_regn_cd"),
//      expr("""CASE WHEN ((`cmls_dest_bin` = 500099) AND (`cmls_dest_cib` = 500099)) THEN '001' ELSE CAST(`cmls_dest_bin_zone_cd` AS STRING) END""").as("cmls_dest_bin_zone_cd"),
//      expr("""cmls_uniq_seq_id_drvd""").as("cmls_uniq_seq_id_drvd"),
//      expr("""concat(CAST(`CMLS_ACCT_USR_BUS_ID_DRVD` AS STRING), `CMLS_ACCT_USR_BUS_ID_CTRY_CD_DRVD`)""").as("ISSR_BID"),
//      expr("""CASE WHEN (`CMLS_SRCE_OF_TRAN_FLG` = 'A') THEN `CMLS_SRCE_BIN` ELSE `CMLS_DEST_BIN` END""").as("TEMP_ACQR_BIN"),
//      expr("""CASE WHEN (`CMLS_SRCE_OF_TRAN_FLG` = 'I') THEN `CMLS_SRCE_BIN` ELSE `CMLS_DEST_BIN` END""").as("TEMP_ISSR_BIN"),
//      expr("""concat(substring(`cmls_cpd_dt`, 1, 4), '-', substring(`cmls_cpd_dt`, 5, 2), '-', substring(`cmls_cpd_dt`, 7, 2))""").as("gmbs_cpd_dt"),
//      expr("""CASE WHEN (NOT (`CMLS_ACQR_IOI_AMT_USD` = 0D)) THEN 'I' ELSE CAST(`CMLS_ACQR_IOI_AMT_USD` AS STRING) END""").as("CMLS_IOI_SA_SRCE_FLG"),
//      expr("""CASE WHEN (`CMLS_TRAN_AMT` = 0D) THEN `CMLS_SETLMT_SRCE_AMT_USD` ELSE `CMLS_TRAN_AMT` END""").as("CMLS_TRAN_AMT"),
//      expr("""concat_ws('', substring(`cmls_cpd_dt`, 3, 4), '00')""").as("gmbs_billing_cylce_id"),
//      lit("N").as("CMLS_SRE_ID_FLG"),
//      lit("smsrfc").as("CMLS_DATA_SOURCE"),
//      lit("smsrfc").as("CMLS_TXN_DATA_SOURCE"),
//      lit("I").as("CMLS_IN_OUT_TAG")
//    )
//
//
//    out
//
//  }
//
//  val rejFlagSmsRfcUDF = udf((CMLS_DEST_FLG: String, CMLS_VE_CS_JRSDCTN_CD_ENR: String, CMLS_SRCE_CIB: Int, CMLS_NSPK_FALLBK_PROCG_RSN_CD: Int, CMLS_VIP_RSI_MSG_CATG: String, CMLS_TRAN_DRCTN: String, CMLS_SMS_REQ_MSG_TYP: String, CMLS_SMS_REC_TYP: String) => {
//
//    if (CMLS_DEST_FLG.trim() != ("E") && CMLS_TRAN_DRCTN.trim() != "") {
//
//      if (CMLS_TRAN_DRCTN.equals("BS") || CMLS_TRAN_DRCTN.equals("BB")) {
//
//        0
//      } else if ((CMLS_SMS_REC_TYP.equals("0") || CMLS_SMS_REC_TYP.equals("1") || CMLS_SMS_REC_TYP.equals("2") || CMLS_SMS_REC_TYP.equals("3") || CMLS_SMS_REC_TYP.equals("5") || CMLS_SMS_REC_TYP.equals("6") || CMLS_SMS_REC_TYP.equals("G") || CMLS_SMS_REQ_MSG_TYP.reverse.padTo(4, '0').reverse.equals("9240") || CMLS_SMS_REQ_MSG_TYP.reverse.padTo(4, '0').reverse.equals("9242")) && CMLS_SMS_REQ_MSG_TYP.reverse.padTo(4, '0').reverse != "0800") {
//
//        0
//      } else {
//        1
//      }
//    } else {
//      1
//    }
//  })
//
//}
//
//
//
